name: Notion Daily Update

on:
  schedule:
    - cron: "0 3 * * *" # Exécution tous les jours à 03:00 UTC
  workflow_dispatch: # Permet de lancer manuellement

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Installer les dépendances
        run: pip install requests python-dotenv

      - name: Exécuter le script notion_movies.py (mise à jour de la DB Notion)
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python notion_movies.py

      - name: Exécuter le script notion_clean_duplicates.py (Nettoyage de la DB Notion)
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python notion_clean_movies.py

      - name: Exécuter le script fetch_movies.py (récupération des films depuis la DB Notion)
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python fetch_movies.py

      - name: Vérifier si des modifications ont été faites
        run: |
          git status
          if [[ -n $(git status --porcelain movies.json) ]]; then
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          else
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          fi

      - name: Commit et push si movies.json a changé
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add movies.json
          git commit -m "Mise à jour automatique de movies.json"
          git push origin main
